# Generated by Django 4.1.3 on 2022-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ip', '0002_student_university_remove_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=10, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='university',
            name='date',
            field=models.CharField(max_length=10, verbose_name='Дата создания'),
        ),
    ]
